services:
  - type: web
    name: gemini-fastapi
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 8000
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://narralokeshreddy859:bXsDLwATm5CGrV68@api.9xmnhuh.mongodb.net/gemini?retryWrites=true&w=majority

        